---
title: "R Quant Adventure"
author: "Craig Orman"
date: "2022-12-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(quantmod)
library(tidyverse)
library(forecast)
```

```{r}
data = readxl::read_excel("./Linkedin Exercises/Algo Trading/ch03/03_02/03_02_Start_R.xlsx")
```

# R finance course
This is the R and Bond trading section of the Linkedin Learning course "Algorithmic Trading and Finance Models with Python, R and Scala by Dr. Michael McDonald

```{r}
getSymbols("AAPL")
```

```{r}

barChart(AAPL, main = "All")
barChart(AAPL, subset="last 28 days")
```

```{r}
rm(AAPL)
getSymbols("GOOG")
barChart(GOOG)
addMACD()
addBBands()
chartSeries(GOOG, subset = "last 60 days")
```

```{r}
rm(GOOG)
getSymbols("MSFT")
summary(MSFT)
```

```{r}
install.packages("BatchGetSymbols")
library(BatchGetSymbols)
```

```{r}
first.date <- Sys.Date()-60
last.date <- Sys.Date()
freq.data<-"daily"
tickers <-c("SPY", "PSEC", "SCHD")
```

```{r}
df = BatchGetSymbols(tickers)
```

```{r}

data = readxl::read_excel("./Linkedin Exercises/Algo Trading/ch03/03_05/03_05_Start_R.xlsx")
linearMod <- lm(Cash ~ EBITDA, data = data[data$Ticker == "AAPL",])
print(linearMod)
```

# End of Module

## Investigate PSEC 

```{r}
getSymbols("PSEC", src = "yahoo")
```


```{r}
psec = data.frame(PSEC)
psec <- cbind(Date = rownames(psec), psec)
rownames(psec) <- 1:nrow(psec)
```


```{r}
ggplot(data = psec[psec$Date > "2022-01-01", ], aes(x = Date, y=PSEC.Close)) +
  geom_point() +
  geom_smooth(method = "loess") +
  ggtitle("PSEC Close") +
  ylab("Open cost in $")
```
#Arima Model

```{r}
start = as.Date("2007/01/01")
end = as.Date("2020/12/31")
dates <- data.frame(Date = seq(start, end, "days"))
```


```{r}
library(forecast)
getSymbols("PSEC", src = "yahoo")
psec = data.frame(PSEC)
rm(PSEC)
colnames(psec) = c("Open", "High", "Low", "Close", "Volume", "Adjusted")
psec <- cbind(Date = rownames(psec), psec)
rownames(psec) <- 1:nrow(psec)
psec$Date <- as.Date(psec$Date)
psec <- merge(dates, psec, all.x = TRUE)
```

```{r}
close = ts(psec[,5],
           start = c(2007),
           frequency = 365)

plot(diff(close))
```

```{r}
ARIMAfit = auto.arima(close, approximation=FALSE,trace=FALSE)
```

```{r}
plot(close)
forecast = predict(ARIMAfit, n.ahead=30)
plot(forecast))
```








